# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.worder::document.form_name

# Model Form Field configuration
form: $/waka/worder/models/document/fields.yaml

# Model Class name
modelClass: Waka\Worder\Models\Document

# Default redirect location
defaultRedirect: waka/worder/documents

# Create page
create:
    title: waka.worder::document.create
    redirect: waka/worder/documents/update/:id
    redirectClose: waka/worder/documents
    form: $/waka/worder/models/document/fields_create.yaml

# Update page
update:
    title: waka.worder::document.update
    redirect: waka/worder/documents/update/:id
    redirectClose: waka/worder/documents

# Preview page
preview:
    title: waka.worder::document.preview_name
