# ===================================
#  Relation Behavior Config
# ===================================




# blocs:
#     label: waka.worder::lang.bloc.code
#     manage:
#         form: $/waka/worder/models/bloc/fields.yaml
#     view:
#         list: $/waka/worder/models/bloc/columns_for_document.yaml
#         toolbarButtons: delete
#         defaultSort:
#             column: sort_order
#             direction: asc



