# ===================================
#  Duplicate Behavior Config
# 
# ATTENTION LE TITRE NE DOIT PAS AVOIR D ESPACE

# Model Class name
modelClass: Waka\Worder\Models\Document

name: documents
title: waka.utils::lang.global.duplicate_theDocument
redirect: backend/waka/worder/documents/update/

duplication:
    #Les champs dans le tableau relation seront cloné et attaché au nouveau model 
    relationsMany:
        - rule_asks
        - rule_fncs
    # relationsBelongsToMany:
    #   - rule_asks
    #   - rule_fncs
  

    #Les champs dans le tableau transformation auront les valeurs listé ci dessous 
    # transformation:
    #     state: Brouillon

    #Les champs qui seront modifié dans le formulaire du popup 
    fields:
        name:
          label: waka.mailer::wakamail.name 
        slug:
          label: waka.mailer::wakamail.slug 

        # _keep:
        #   label: Dupliquer dans ce projet
        #   type: checkbox
        #   default: 0

        # project:
        #   label: Choisissez un projet
        #   type: relation
        #   placeholder: -- choisissez un projet --
        #   select: concat(name,' | ' ,code)
        #   trigger:
        #     action: hide
        #     field: _keep
        #     condition: checked



          
    
        



